export interface OrderStatus {
    id: number;
    name: string;
    type: "completed" | "in_progress" | "cancelled" | "pending" | "new";
}

export interface Order {
    id: number;
    serviceName: string;
    description: string;
    price: number;
    district: string;
    publishedDate: string;
    phone: string;
    firstName: string;
    lastName: string;
    status: OrderStatus;
}

export const ordersData: Order[] = [
    {
        id: 1023947,
        serviceName: "Установка кондиционера",
        description: "Требуется установка сплит-системы в двухкомнатной квартире. Наружный блок на фасаде, внутренний в гостиной.",
        price: 1500000,
        district: "Чиланзарский",
        publishedDate: "2026-01-25",
        phone: "+998901234567",
        firstName: "Иван",
        lastName: "Петров",
        status: { id: 5, name: "Новый", type: "new" },
    },
    {
        id: 1023952,
        serviceName: "Ремонт стиральной машины",
        description: "Стиральная машина Samsung не сливает воду. Нужна диагностика и ремонт на месте.",
        price: 800000,
        district: "Мирзо-Улугбекский",
        publishedDate: "2026-01-24",
        phone: "+998931234567",
        firstName: "Алексей",
        lastName: "Смирнов",
        status: { id: 2, name: "В работе", type: "in_progress" },
    },
    {
        id: 1023961,
        serviceName: "Уборка квартиры",
        description: "Генеральная уборка трёхкомнатной квартиры после ремонта. Площадь 85 кв.м.",
        price: 350000,
        district: "Яккасарайский",
        publishedDate: "2026-01-23",
        phone: "+998941234567",
        firstName: "Мария",
        lastName: "Козлова",
        status: { id: 3, name: "Отменён", type: "cancelled" },
    },
    {
        id: 1023978,
        serviceName: "Сантехнические работы",
        description: "Замена смесителя и установка унитаза в ванной комнате. Материалы свои.",
        price: 1200000,
        district: "Юнусабадский",
        publishedDate: "2026-01-22",
        phone: "+998951234567",
        firstName: "Дмитрий",
        lastName: "Волков",
        status: { id: 1, name: "Завершён", type: "completed" },
    },
    {
        id: 1023985,
        serviceName: "Электромонтажные работы",
        description: "Прокладка электропроводки в новостройке. Три комнаты, кухня, санузел.",
        price: 2000000,
        district: "Сергелийский",
        publishedDate: "2026-01-21",
        phone: "+998971234567",
        firstName: "Ольга",
        lastName: "Новикова",
        status: { id: 4, name: "Ожидание", type: "pending" },
    },
    {
        id: 1024001,
        serviceName: "Поклейка обоев",
        description: "Поклейка виниловых обоев в двух комнатах. Стены подготовлены, обои в наличии.",
        price: 950000,
        district: "Шайхантахурский",
        publishedDate: "2026-01-20",
        phone: "+998991234567",
        firstName: "Сергей",
        lastName: "Морозов",
        status: { id: 2, name: "В работе", type: "in_progress" },
    },
    {
        id: 1024013,
        serviceName: "Укладка плитки",
        description: "Укладка керамогранита на пол в кухне и коридоре. Площадь 25 кв.м.",
        price: 1800000,
        district: "Алмазарский",
        publishedDate: "2026-01-19",
        phone: "+998901112233",
        firstName: "Анна",
        lastName: "Соколова",
        status: { id: 1, name: "Завершён", type: "completed" },
    },
    {
        id: 1024027,
        serviceName: "Установка дверей",
        description: "Установка трёх межкомнатных дверей. Двери уже куплены, нужен только монтаж.",
        price: 600000,
        district: "Бектемирский",
        publishedDate: "2026-01-18",
        phone: "+998933344556",
        firstName: "Владимир",
        lastName: "Лебедев",
        status: { id: 5, name: "Новый", type: "new" },
    },
    {
        id: 1024034,
        serviceName: "Покраска стен",
        description: "Покраска стен водоэмульсионной краской в спальне и детской. Стены выровнены.",
        price: 450000,
        district: "Учтепинский",
        publishedDate: "2026-01-17",
        phone: "+998945556677",
        firstName: "Екатерина",
        lastName: "Кузнецова",
        status: { id: 1, name: "Завершён", type: "completed" },
    },
    {
        id: 1024048,
        serviceName: "Сборка мебели",
        description: "Сборка кухонного гарнитура и шкафа-купе. Мебель от производителя, инструкция в комплекте.",
        price: 300000,
        district: "Мирабадский",
        publishedDate: "2026-01-16",
        phone: "+998977788990",
        firstName: "Артём",
        lastName: "Попов",
        status: { id: 3, name: "Отменён", type: "cancelled" },
    },
    {
        id: 1024055,
        serviceName: "Ремонт холодильника",
        description: "Холодильник LG перестал морозить. Компрессор работает, но температура не снижается.",
        price: 700000,
        district: "Чиланзарский",
        publishedDate: "2026-01-15",
        phone: "+998901122334",
        firstName: "Наталья",
        lastName: "Васильева",
        status: { id: 2, name: "В работе", type: "in_progress" },
    },
    {
        id: 1024063,
        serviceName: "Монтаж натяжного потолка",
        description: "Установка матового натяжного потолка в зале. Площадь 30 кв.м., один уровень.",
        price: 2500000,
        district: "Юнусабадский",
        publishedDate: "2026-01-14",
        phone: "+998934455667",
        firstName: "Павел",
        lastName: "Михайлов",
        status: { id: 1, name: "Завершён", type: "completed" },
    },
    {
        id: 1024079,
        serviceName: "Замена окон",
        description: "Демонтаж старых деревянных окон и установка пластиковых. Четыре оконных проёма.",
        price: 3200000,
        district: "Яккасарайский",
        publishedDate: "2026-01-13",
        phone: "+998946677889",
        firstName: "Татьяна",
        lastName: "Фёдорова",
        status: { id: 4, name: "Ожидание", type: "pending" },
    },
    {
        id: 1024088,
        serviceName: "Химчистка дивана",
        description: "Химчистка углового дивана и двух кресел. Ткань — велюр, пятна от кофе и еды.",
        price: 250000,
        district: "Мирзо-Улугбекский",
        publishedDate: "2026-01-12",
        phone: "+998957788990",
        firstName: "Андрей",
        lastName: "Егоров",
        status: { id: 5, name: "Новый", type: "new" },
    },
    {
        id: 1024095,
        serviceName: "Установка видеонаблюдения",
        description: "Установка четырёх камер видеонаблюдения в частном доме с подключением к видеорегистратору.",
        price: 1700000,
        district: "Сергелийский",
        publishedDate: "2026-01-11",
        phone: "+998969900112",
        firstName: "Юлия",
        lastName: "Козлова",
        status: { id: 1, name: "Завершён", type: "completed" },
    },
];
